image: gcc

stages:
  - build
  - test

build:
  stage: build
  before_script:
    - apt update && apt -y install cmake
  script:
    - mkdir -p build
    - cmake -B build -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug
    - cmake --build build -j10
  artifacts:
    paths:
      - build/test_17
      - build/test_20
      - build/test_23

test:
  stage: test
  script:
    - ./build/test_17
    - ./build/test_20
    - ./build/test_23
