image: gcc

build:
  stage: build
  before_script:
    - apt update && apt -y install cmake
    - git clone https://github.com/google/googletest
    - cd googletest
    - mkdir -p build
    - cmake -B build
    - cmake --build build
    - cmake --build build --target install
    - cd ..
  script:
    - mkdir -p build
    - cmake -B build -DBUILD_TESTS=ON
    - cmake --build build
  artifacts:
    cache:
      - googletest
      - build

test:
  stage: test
  script:
    - ./build/test/test_all

deploy:
  stage: deploy
  script: 
      - cmake --build build --target install
  environment: production

