image: gcc

stages:
  - build
  - test

build:
  stage: build
  before_script:
    - apt update && apt -y install cmake
  script:
    - mkdir -p build
    - cmake -B build -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug
    - cmake --build build
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - cd build
    - ctest -j10 -C Debug --output-on-failure -R ^
